# Generated by Django 5.2.5 on 2025-08-25 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2text', models.CharField(default='WELCOME TO LUGX', max_length=200)),
                ('h6text', models.CharField(default='BEST GAMING SITE EVER', max_length=200)),
                ('ptext', models.TextField()),
                ('pricetext', models.CharField(default='$22', max_length=200)),
                ('offertext', models.CharField(default='-40%', max_length=200)),
                ('buttontext', models.CharField(default='SEARCH', max_length=200)),
                ('Gameimg', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureimg1', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext1', models.CharField(default='FREE STORAGE', max_length=200)),
                ('featureimg2', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext2', models.CharField(default='USER MORE', max_length=200)),
                ('featureimg3', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext3', models.CharField(default='REPLY READY', max_length=200)),
                ('featureimg4', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext4', models.CharField(default='EASY LAYOUT', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gamesection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(default='TRENDING', max_length=200)),
                ('h2text', models.CharField(default='Trending Games', max_length=200)),
                ('buttontext', models.CharField(default='View All', max_length=200)),
                ('pricetextoriginal1', models.CharField(max_length=200)),
                ('pricetextlowered1', models.CharField(max_length=200)),
                ('gamename1', models.CharField(max_length=200)),
                ('gamegenre1', models.CharField(max_length=200)),
                ('gameimg1', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('pricetext2', models.CharField(max_length=200)),
                ('gamename2', models.CharField(max_length=200)),
                ('gamegenre2', models.CharField(max_length=200)),
                ('gameimg2', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('pricetextoriginal3', models.CharField(max_length=200)),
                ('pricetextlowered3', models.CharField(max_length=200)),
                ('gamename3', models.CharField(max_length=200)),
                ('gamegenre3', models.CharField(max_length=200)),
                ('gameimg3', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('pricetext4', models.CharField(max_length=200)),
                ('gamename4', models.CharField(max_length=200)),
                ('gamegenre4', models.CharField(max_length=200)),
                ('gameimg4', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Gamesection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(default='TOP GAMES', max_length=200)),
                ('h2text', models.CharField(default='Most played', max_length=200)),
                ('buttontext1', models.CharField(default='View All', max_length=200)),
                ('buttontext2', models.CharField(default='Explore', max_length=200)),
                ('gamename1', models.CharField(max_length=200)),
                ('gamegenre1', models.CharField(max_length=200)),
                ('gameimg1', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename2', models.CharField(max_length=200)),
                ('gamegenre2', models.CharField(max_length=200)),
                ('gameimg2', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename3', models.CharField(max_length=200)),
                ('gamegenre3', models.CharField(max_length=200)),
                ('gameimg3', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename4', models.CharField(max_length=200)),
                ('gamegenre4', models.CharField(max_length=200)),
                ('gameimg4', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename5', models.CharField(max_length=200)),
                ('gamegenre5', models.CharField(max_length=200)),
                ('gameimg5', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename6', models.CharField(max_length=200)),
                ('gamegenre6', models.CharField(max_length=200)),
                ('gameimg6', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Gamesection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(default='CATEGORIES', max_length=200)),
                ('h2text', models.CharField(default='Top Categories', max_length=200)),
                ('gamegenre1', models.CharField(max_length=200)),
                ('gameimg1', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre2', models.CharField(max_length=200)),
                ('gameimg2', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre3', models.CharField(max_length=200)),
                ('gameimg3', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre4', models.CharField(max_length=200)),
                ('gameimg4', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre5', models.CharField(max_length=200)),
                ('gameimg5', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('texthtml1', models.CharField(default='Home', max_length=200)),
                ('texthtml2', models.CharField(default='Our shop', max_length=200)),
                ('texthtml3', models.CharField(default='Product details', max_length=200)),
                ('texthtml4', models.CharField(default='Contact us', max_length=200)),
                ('signuptext', models.CharField(default='Sign up', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.EmailField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Search',
                'verbose_name_plural': 'User Searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
