# Generated by Django 5.2.5 on 2025-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('texthtml1', models.CharField(default='Home', max_length=200)),
                ('texthtml2', models.CharField(default='Our shop', max_length=200)),
                ('texthtml3', models.CharField(default='Product details', max_length=200)),
                ('texthtml4', models.CharField(default='Contact us', max_length=200)),
                ('Signuptext', models.CharField(default='Sign up', max_length=200)),
            ],
        ),
    ]
