# Generated by Django 5.2.5 on 2025-08-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='Signuptext',
            new_name='signuptext',
        ),
    ]
