# Generated by Django 5.2.5 on 2025-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
