# Generated by Django 5.2.5 on 2025-08-19 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_signuptext_header_signuptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2text', models.CharField(default='WELCOME TO LUGX', max_length=200)),
                ('h6text', models.CharField(default='BEST GAMING SITE EVER', max_length=200)),
                ('ptext', models.TextField()),
                ('pricetext', models.CharField(default='$22', max_length=200)),
                ('offertext', models.CharField(default='-40%', max_length=200)),
                ('buttontext', models.CharField(default='SEARCH', max_length=200)),
                ('Gameimg', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Search',
                'verbose_name_plural': 'User Searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
