# Generated by Django 5.2.5 on 2025-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_email_profile_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('texthtml1', models.CharField(default='Home', max_length=200)),
                ('texthtml2', models.CharField(default='Our shop', max_length=200)),
                ('texthtml3', models.CharField(default='Product details', max_length=200)),
                ('texthtml4', models.CharField(default='Contact us', max_length=200)),
                ('signuptext', models.CharField(default='Sign up', max_length=200)),
            ],
        ),
    ]
