# Generated by Django 5.2.5 on 2025-08-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_container_usersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureimg1', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext1', models.CharField(default='FREE STORAGE', max_length=200)),
                ('featureimg2', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext2', models.CharField(default='USER MORE', max_length=200)),
                ('featureimg3', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext3', models.CharField(default='REPLY READY', max_length=200)),
                ('featureimg4', models.ImageField(blank=True, upload_to='Featureimg/')),
                ('featuretext4', models.CharField(default='EASY LAYOUT', max_length=200)),
            ],
        ),
    ]
