# Generated by Django 5.2.5 on 2025-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(default='TRENDING', max_length=200)),
                ('h2text', models.CharField(default='Trending Games', max_length=200)),
                ('buttontext', models.CharField(default='View All', max_length=200)),
                ('pricetextoriginal1', models.CharField(max_length=200)),
                ('pricetextlowered1', models.CharField(max_length=200)),
                ('gamename1', models.CharField(max_length=200)),
                ('gamegenre1', models.CharField(max_length=200)),
                ('gameimg1', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('pricetext2', models.CharField(max_length=200)),
                ('gamename2', models.CharField(max_length=200)),
                ('gmegenre2', models.CharField(max_length=200)),
                ('gameimg2', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('pricetextoriginal3', models.CharField(max_length=200)),
                ('pricetextlowered3', models.CharField(max_length=200)),
                ('gamename3', models.CharField(max_length=200)),
                ('gamegenre3', models.CharField(max_length=200)),
                ('gameimg3', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('pricetext4', models.CharField(max_length=200)),
                ('gamename4', models.CharField(max_length=200)),
                ('gamegenre4', models.CharField(max_length=200)),
                ('gameimg4', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
    ]
