# Generated by Django 5.2.5 on 2025-08-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_headershop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContanierShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigtext', models.CharField(max_length=200)),
                ('smalltext1', models.CharField(max_length=200)),
                ('smalltext2', models.CharField(max_length=200)),
            ],
        ),
    ]
