# Generated by Django 5.2.5 on 2025-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contaniershop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtertext1', models.CharField(max_length=200)),
                ('filtertext2', models.CharField(max_length=200)),
                ('filtertext3', models.CharField(max_length=200)),
                ('filtertext4', models.CharField(max_length=200)),
            ],
        ),
    ]
