# Generated by Django 5.2.5 on 2025-08-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gamesection1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesection1',
            old_name='gmegenre2',
            new_name='gamegenre2',
        ),
    ]
