# Generated by Django 5.2.5 on 2025-08-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shopfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBuysection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section name (e.g. Top Discounts, Bestsellers)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=200)),
                ('gamegenre', models.CharField(max_length=200)),
                ('pricetextoriginal', models.CharField(max_length=200)),
                ('pricetextlowered', models.CharField(max_length=200)),
                ('gameimg', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('shop_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main.shopbuysection')),
            ],
        ),
    ]
