# Generated by Django 5.2.5 on 2025-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_gmegenre2_gamesection1_gamegenre2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(default='TOP GAMES', max_length=200)),
                ('h2text', models.CharField(default='Most played', max_length=200)),
                ('buttontext1', models.CharField(default='View All', max_length=200)),
                ('buttontext2', models.CharField(default='Explore', max_length=200)),
                ('gamename1', models.CharField(max_length=200)),
                ('gamegenre1', models.CharField(max_length=200)),
                ('gameimg1', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename2', models.CharField(max_length=200)),
                ('gamegenre2', models.CharField(max_length=200)),
                ('gameimg2', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename3', models.CharField(max_length=200)),
                ('gamegenre3', models.CharField(max_length=200)),
                ('gameimg3', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename4', models.CharField(max_length=200)),
                ('gamegenre4', models.CharField(max_length=200)),
                ('gameimg4', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename5', models.CharField(max_length=200)),
                ('gamegenre5', models.CharField(max_length=200)),
                ('gameimg5', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamename6', models.CharField(max_length=200)),
                ('gamegenre6', models.CharField(max_length=200)),
                ('gameimg6', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
    ]
