# Generated by Django 5.2.5 on 2025-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shopbuysection_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_section_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(max_length=200)),
                ('h2text', models.CharField(max_length=400)),
                ('h2bluetext', models.CharField(max_length=100)),
                ('ptext', models.TextField()),
                ('buttontext', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(max_length=200)),
                ('h2text', models.CharField(max_length=400)),
                ('h2bluetext', models.CharField(max_length=100)),
                ('buttontext', models.CharField(max_length=200)),
            ],
        ),
    ]
