# Generated by Django 5.2.5 on 2025-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gamesection2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h6redtext', models.CharField(default='CATEGORIES', max_length=200)),
                ('h2text', models.CharField(default='Top Categories', max_length=200)),
                ('gamegenre1', models.CharField(max_length=200)),
                ('gameimg1', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre2', models.CharField(max_length=200)),
                ('gameimg2', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre3', models.CharField(max_length=200)),
                ('gameimg3', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre4', models.CharField(max_length=200)),
                ('gameimg4', models.ImageField(blank=True, upload_to='Gamesimg/')),
                ('gamegenre5', models.CharField(max_length=200)),
                ('gameimg5', models.ImageField(blank=True, upload_to='Gamesimg/')),
            ],
        ),
    ]
