# Generated by Django 5.2.5 on 2025-08-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shop_section_text_subscribe_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderShop',
        ),
    ]
